    #!/usr/bin/env python3
"""
GGUF Workbench V2.1 - Main entry point.

This file imports from the gguf_workbench package for backwards compatibility.
For development, the package is at gguf_workbench/app.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from gguf_workbench import (
    # Package
    build_app,
    # Parser
    load_manifest,
    load_gguf,
    GGUFManifest,
    TensorInfo,
    GGUFParser,
    GGUFParseError,
    BinaryReader,
    manifest_to_dict,
    manifest_from_dict,
    manifest_summary,
    align_offset,
    # Tensor ops
    decode_tensor,
    encode_tensor,
    transform_array,
    build_transform_preview,
    parse_indices,
    parse_slice_spec,
    bf16_to_f32,
    f32_to_bf16,
    resolve_decode_kind,
    # Validation
    validate_output_path,
    default_output_path,
    # Compare
    compare_gguf,
    # Batch
    BatchOperation,
    write_tensor_patch,
    batch_op_to_dict,
    batch_op_from_dict,
    batch_add_scalar,
    batch_add_transform,
    batch_add_slice,
    render_batch_queue,
    apply_batch,
    clear_batch,
    # App handlers
    filter_tensor_table,
    inspect_tensor,
    on_load,
    patch_scalar,
    patch_transform,
    patch_slice,
    preview_transform,
    preview_slice_edit,
    # Constants
    APP_TITLE,
    DEFAULT_ALIGNMENT,
    GGUF_MAGIC,
    SUPPORTED_VERSIONS,
    GGUF_TYPE_UINT8,
    GGUF_TYPE_INT8,
    GGUF_TYPE_UINT16,
    GGUF_TYPE_INT16,
    GGUF_TYPE_UINT32,
    GGUF_TYPE_INT32,
    GGUF_TYPE_FLOAT32,
    GGUF_TYPE_BOOL,
    GGUF_TYPE_STRING,
    GGUF_TYPE_ARRAY,
    GGUF_TYPE_UINT64,
    GGUF_TYPE_INT64,
    GGUF_TYPE_FLOAT64,
    GGML_TYPE_F32,
    GGML_TYPE_F16,
    GGML_TYPE_BF16,
    GGML_TYPE_NAMES,
    EDITABLE_TYPE_NAMES,
)

# Backwards compatibility - re-export all imports
__all__ = [
    "build_app",
    "load_manifest",
    "load_gguf",
    "GGUFManifest",
    "TensorInfo",
    "GGUFParser",
    "GGUFParseError",
    "BinaryReader",
    "manifest_to_dict",
    "manifest_from_dict",
    "manifest_summary",
    "align_offset",
    "decode_tensor",
    "encode_tensor",
    "transform_array",
    "build_transform_preview",
    "parse_indices",
    "parse_slice_spec",
    "bf16_to_f32",
    "f32_to_bf16",
    "resolve_decode_kind",
    "validate_output_path",
    "default_output_path",
    "compare_gguf",
    "BatchOperation",
    "write_tensor_patch",
    "batch_op_to_dict",
    "batch_op_from_dict",
    "batch_add_scalar",
    "batch_add_transform",
    "batch_add_slice",
    "render_batch_queue",
    "apply_batch",
    "clear_batch",
    "filter_tensor_table",
    "inspect_tensor",
    "on_load",
    "patch_scalar",
    "patch_transform",
    "patch_slice",
    "preview_transform",
    "preview_slice_edit",
    "APP_TITLE",
    "DEFAULT_ALIGNMENT",
    "GGUF_MAGIC",
    "SUPPORTED_VERSIONS",
    "GGUF_TYPE_UINT8",
    "GGUF_TYPE_INT8",
    "GGUF_TYPE_UINT16",
    "GGUF_TYPE_INT16",
    "GGUF_TYPE_UINT32",
    "GGUF_TYPE_INT32",
    "GGUF_TYPE_FLOAT32",
    "GGUF_TYPE_BOOL",
    "GGUF_TYPE_STRING",
    "GGUF_TYPE_ARRAY",
    "GGUF_TYPE_UINT64",
    "GGUF_TYPE_INT64",
    "GGUF_TYPE_FLOAT64",
    "GGML_TYPE_F32",
    "GGML_TYPE_F16",
    "GGML_TYPE_BF16",
    "GGML_TYPE_NAMES",
    "EDITABLE_TYPE_NAMES",
]

if __name__ == "__main__":
    build_app().launch()
