from .constants import (
    APP_TITLE,
    DEFAULT_ALIGNMENT,
    GGUF_MAGIC,
    SUPPORTED_VERSIONS,
    GGUF_TYPE_UINT8,
    GGUF_TYPE_INT8,
    GGUF_TYPE_UINT16,
    GGUF_TYPE_INT16,
    GGUF_TYPE_UINT32,
    GGUF_TYPE_INT32,
    GGUF_TYPE_FLOAT32,
    GGUF_TYPE_BOOL,
    GGUF_TYPE_STRING,
    GGUF_TYPE_ARRAY,
    GGUF_TYPE_UINT64,
    GGUF_TYPE_INT64,
    GGUF_TYPE_FLOAT64,
    GGML_TYPE_F32,
    GGML_TYPE_F16,
    GGML_TYPE_BF16,
    GGML_TYPE_NAMES,
    EDITABLE_TYPE_NAMES,
    QUANTIZED_TYPE_NAMES,
)

from .parser import (
    GGUFParseError,
    BinaryReader,
    TensorInfo,
    GGUFManifest,
    GGUFParser,
    load_gguf,
    load_manifest,
    manifest_to_dict,
    manifest_from_dict,
    manifest_summary,
    align_offset,
)

from .tensor_ops import (
    bf16_to_f32,
    f32_to_bf16,
    resolve_decode_kind,
    decode_tensor,
    encode_tensor,
    transform_array,
    build_transform_preview,
    parse_indices,
    parse_slice_spec,
    dequantize_q8_0,
    dequantize_q4_0,
    dequantize_q4_k,
    dequantize_q5_0,
    dequantize_q5_k,
    dequantize_q6_k,
    dequantize_q2_k,
    dequantize_q3_k,
    dequantize_iq4_xs,
)

from .validation import (
    validate_output_path,
    default_output_path,
)

from .compare import compare_gguf

from .batch import (
    BatchOperation,
    write_tensor_patch,
    batch_op_to_dict,
    batch_op_from_dict,
    batch_add_scalar,
    batch_add_transform,
    batch_add_slice,
    render_batch_queue,
    apply_batch,
    clear_batch,
)

from .app import (
    build_app,
    filter_tensor_table,
    inspect_tensor,
    inspect_tensor_mri,
    on_load,
    patch_scalar,
    patch_transform,
    patch_slice,
    preview_transform,
    preview_slice_edit,
)

from .mri_viz import (
    compute_tensor_stats,
    plot_histogram,
    plot_heatmap,
    plot_layer_summary,
    plot_model_overview,
    get_tensor_quantization_info,
)

__all__ = [
    "APP_TITLE",
    "DEFAULT_ALIGNMENT",
    "GGUF_MAGIC",
    "SUPPORTED_VERSIONS",
    "GGUF_TYPE_UINT8",
    "GGUF_TYPE_INT8",
    "GGUF_TYPE_UINT16",
    "GGUF_TYPE_INT16",
    "GGUF_TYPE_UINT32",
    "GGUF_TYPE_INT32",
    "GGUF_TYPE_FLOAT32",
    "GGUF_TYPE_BOOL",
    "GGUF_TYPE_STRING",
    "GGUF_TYPE_ARRAY",
    "GGUF_TYPE_UINT64",
    "GGUF_TYPE_INT64",
    "GGUF_TYPE_FLOAT64",
    "GGML_TYPE_F32",
    "GGML_TYPE_F16",
    "GGML_TYPE_BF16",
    "GGML_TYPE_NAMES",
    "EDITABLE_TYPE_NAMES",
    "QUANTIZED_TYPE_NAMES",
    "GGUFParseError",
    "BinaryReader",
    "TensorInfo",
    "GGUFManifest",
    "GGUFParser",
    "load_gguf",
    "load_manifest",
    "manifest_to_dict",
    "manifest_from_dict",
    "manifest_summary",
    "align_offset",
    "bf16_to_f32",
    "f32_to_bf16",
    "resolve_decode_kind",
    "decode_tensor",
    "encode_tensor",
    "transform_array",
    "build_transform_preview",
    "parse_indices",
    "parse_slice_spec",
    "dequantize_q8_0",
    "dequantize_q4_0",
    "dequantize_q4_k",
    "dequantize_q5_0",
    "dequantize_q5_k",
    "dequantize_q6_k",
    "dequantize_q2_k",
    "dequantize_q3_k",
    "dequantize_iq4_xs",
    "validate_output_path",
    "default_output_path",
    "compare_gguf",
    "BatchOperation",
    "write_tensor_patch",
    "batch_op_to_dict",
    "batch_op_from_dict",
    "batch_add_scalar",
    "batch_add_transform",
    "batch_add_slice",
    "render_batch_queue",
    "apply_batch",
    "clear_batch",
    "build_app",
    "filter_tensor_table",
    "inspect_tensor",
    "inspect_tensor_mri",
    "on_load",
    "patch_scalar",
    "patch_transform",
    "patch_slice",
    "preview_transform",
    "preview_slice_edit",
    "compute_tensor_stats",
    "plot_histogram",
    "plot_heatmap",
    "plot_layer_summary",
    "plot_model_overview",
    "get_tensor_quantization_info",
]

__version__ = "2.1.0"
